services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naya-fastapi-prod
    ports:
      - "8000:8000"
    env_file:
      - .env   # Aquí debe estar tu DATABASE_URL de Supabase y llaves
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: naya-redis-prod
    ports:
      - "6379:6379"
