from enum import Enum


class UserRoles(Enum):
    PATIENT = "PATIENT"
    THERAPIST = "THERAPIST"


class VerificationModels(Enum):
    VERIFICATION_CODE_MODEL = "VERIFICATION_CODE_MODEL"
    CONNECTION_CODE_MODEL = "CONNECTION_CODE_MODEL"
    VERIFICATION_CODE_PASSWORD_RESET_MODEL = "VERIFICATION_CODE_PASSWORD_RESET_MODEL"

class ActivityTypes (Enum):
    KINESTESICO= "KINESTHETIC"
    VISUAL = "VISUAL"
    AUDITORY= "AUDITORY"