"""create_situations_table

Revision ID: 01701732a213
Revises: 48370727be17
Create Date: 2025-07-10 20:19:47.135646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '01701732a213'
down_revision: Union[str, None] = '48370727be17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('story', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('emotion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('situations')
    # ### end Alembic commands ###
