"""create_patient_table

Revision ID: 1d4418412945
Revises: 3937d738c806
Create Date: 2025-06-19 19:24:29.127959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1d4418412945"
down_revision: Union[str, None] = "3937d738c806"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_connected", sa.Boolean(), nullable=False),
        sa.Column("animal_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_patient_user"),
        sa.ForeignKeyConstraint(
            ["animal_id"], ["animals.id"], name="fk_patient_animal"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_patient_user"),
    )

    op.create_index(op.f("ix_patients_user_id"), "patients", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_patients_animal_id"), "patients", ["animal_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_animal_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_user_id"), table_name="patients")

    op.drop_table("patients")
    # ### end Alembic commands ###
