"""create_stories_table

Revision ID: 2c66c7844a18
Revises: 3cfe839ed677
Create Date: 2025-07-25 17:57:47.242030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2c66c7844a18'
down_revision: Union[str, None] = '3cfe839ed677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('stage_1', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('stage_2', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    # ### end Alembic commands ###
