"""add_column_image_url_in_situations

Revision ID: 7355f2f3fe5c
Revises: 00bdd9dd5ecc
Create Date: 2025-08-05 06:04:30.539152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7355f2f3fe5c'
down_revision: Union[str, None] = '00bdd9dd5ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('situations', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('situations', 'image_url')
    # ### end Alembic commands ###
