"""create_energy_table

Revision ID: a9446717a25b
Revises: 3e47a2df233c
Create Date: 2025-07-11 20:38:28.579204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9446717a25b'
down_revision: Union[str, None] = '3e47a2df233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_energy', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('last_charge', sa.DateTime(), nullable=False),
    sa.Column('recharge_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energies')
    # ### end Alembic commands ###
