"""create_advices_shown_table

Revision ID: bab5434ecdc7
Revises: d16af80a19e2
Create Date: 2025-07-11 23:30:47.907902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bab5434ecdc7'
down_revision: Union[str, None] = 'd16af80a19e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advices_shown',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('advice_id', sa.Uuid(), nullable=False),
    sa.Column('date_shown', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advice_id'], ['advices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    sa.UniqueConstraint('date_shown', name='uq_advicesShown_dateShown')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advices_shown')
    # ### end Alembic commands ###
