"""create_pictures_table

Revision ID: c1bb91479aa5
Revises: 6876638b87dc
Create Date: 2025-06-20 22:16:29.492416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c1bb91479aa5"
down_revision: Union[str, None] = "6876638b87dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pictures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("picture", sa.String(length=255), nullable=False),
        sa.Column("is_profile", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pictures")
    # ### end Alembic commands ###
