"""create_veredict_table

Revision ID: d0fd99e346f4
Revises: f894fd303954
Create Date: 2025-07-25 19:15:09.467428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd0fd99e346f4'
down_revision: Union[str, None] = 'f894fd303954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veredicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('emotion_id', sa.Uuid(), nullable=False),
    sa.Column('min_range', sa.Float(), nullable=False),
    sa.Column('max_range', sa.Integer(), nullable=False),
    sa.Column('veredict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veredicts')
    # ### end Alembic commands ###
